"""empty message

Revision ID: 89863742ac2b
Revises: 
Create Date: 2023-09-05 00:25:26.691419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89863742ac2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('descriptions')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
